# Generated by Django 5.1.4 on 2024-12-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_newsletterrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PortfolioPost',
        ),
    ]
