# Generated by Django 5.1.4 on 2024-12-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_resource_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasenotes',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
