# Generated by Django 5.1.4 on 2024-12-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_releasenotes_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasenotes',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
