# Generated by Django 5.1.4 on 2024-12-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
