# Generated by Django 5.1.4 on 2026-05-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_resource_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
