# Generated by Django 5.1.4 on 2024-12-08 13:21

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPostGer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('date_posted', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('salary', models.CharField(blank=True, max_length=300)),
                ('start_date', models.CharField(blank=True, max_length=300)),
                ('duration', models.CharField(blank=True, max_length=300)),
                ('location', models.CharField(blank=True, max_length=300)),
                ('job_description', ckeditor.fields.RichTextField()),
                ('job_requirements', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
