# Generated by Django 5.1.4 on 2024-12-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0002_jobpostger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobPostGer',
        ),
    ]
