# Generated by Django 5.1.4 on 2024-12-09 11:52

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0004_jobpostgerman'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostgerman',
            name='publish_boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postgerman',
            name='publish_boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='releasenotesgerman',
            name='publish_boolean',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SolutionGerman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True)),
                ('snippet', models.TextField(blank=True, max_length=600)),
                ('image', ckeditor_uploader.fields.RichTextUploadingField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish_boolean', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
