# Generated by Django 5.1.4 on 2024-12-09 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0005_jobpostgerman_publish_boolean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postgerman',
            name='solution_boolean',
        ),
    ]
