# Generated by Django 5.1.4 on 2024-12-11 10:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0006_remove_postgerman_solution_boolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplicationGerman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=500)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True, max_length=10000)),
                ('resume_upload', models.FileField(upload_to='media/job_application_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('jobpost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobapplication', to='blog_ger.jobpostgerman')),
            ],
        ),
    ]
