# Generated by Django 5.1.4 on 2024-12-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0007_jobapplicationgerman'),
    ]

    operations = [
        migrations.AddField(
            model_name='releasenotesgerman',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
