# Generated by Django 5.1.4 on 2024-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_ger', '0008_releasenotesgerman_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postgerman',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
